### ISSUE TITLE
Rekor client leaks goroutine

### ISSUE THREAD

**Issue by datosh** [sigstore/rekor#1094]
**Description**

```
package example

import (
	"testing"

	"github.com/sigstore/rekor/pkg/client"
	"github.com/sigstore/rekor/pkg/generated/client/index"
	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}

func TestRekor_SearchByHash(t *testing.T) {
	rekor, _ := client.GetRekorClient("https://rekor.sigstore.dev")
	params := index.NewSearchIndexParams()
	rekor.Index.SearchIndex(params)
}
```

results in

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 16 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 16 [IO wait]:
internal/poll.runtime_pollWait(0x7f12b0df7858, 0x72)
	/usr/local/go/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc00031d398, 0xc00035ec00?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00031d380, {0xc00035ec00, 0x1300, 0x1300})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x415
net.(*netFD).Read(0xc00031d380, {0xc00035ec00, 0x1300, 0x1300})
	/usr/local/go/src/net/fd_posix.go:55 +0x51
net.(*conn).Read(0xc00051c060, {0xc00035ec00, 0x1300, 0x1300})
	/usr/local/go/src/net/net.go:183 +0xb1
crypto/tls.(*atLeastReader).Read(0xc0004b8000, {0xc00035ec00, 0x1300, 0x1300})
	/usr/local/go/src/crypto/tls/conn.go:787 +0x86
bytes.(*Buffer).ReadFrom(0xc0004ce278, {0x1241520, 0xc0004b8000})
	/usr/local/go/src/bytes/buffer.go:202 +0x113
crypto/tls.(*Conn).readFromUntil(0xc0004ce000, {0x1243a60?, 0xc00051c060}, 0x5)
	/usr/local/go/src/crypto/tls/conn.go:809 +0x1f3
crypto/tls.(*Conn).readRecordOrCCS(0xc0004ce000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:616 +0x417
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc0004ce000, {0xc000018000, 0x1000, 0x1000100000001?})
	/usr/local/go/src/crypto/tls/conn.go:1287 +0x29d
bufio.(*Reader).Read(0xc0007232c0, {0xc00071c660, 0x9, 0x9})
	/usr/local/go/src/bufio/bufio.go:237 +0x4f3
io.ReadAtLeast({0x12413e0, 0xc0007232c0}, {0xc00071c660, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0xde
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
net/http.http2readFrameHeader({0xc00071c660?, 0x9?, 0x9?}, {0x12413e0?, 0xc0007232c0?})
	/usr/local/go/src/net/http/h2_bundle.go:1565 +0x96
net/http.(*http2Framer).ReadFrame(0xc00071c620)
	/usr/local/go/src/net/http/h2_bundle.go:1829 +0x10f
net/http.(*http2clientConnReadLoop).run(0xc0002e5f78)
	/usr/local/go/src/net/http/h2_bundle.go:8875 +0x1f9
net/http.(*http2ClientConn).readLoop(0xc0004cc180)
	/usr/local/go/src/net/http/h2_bundle.go:8771 +0x9f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7478 +0x14ec
]
```

**Version**

`github.com/sigstore/rekor v0.12.2`

**Comment by cpanato** [comment]
cc @asraa @priyawadhwa
